require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe JourneysController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Journey. As you add validations to Journey, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {title: "A valid title", body: "A valid selection of body text"} }

  let(:blank_title) { {title: "", body: "A valid body"} }
  let(:blank_body) { {title: "A valid title", body: ""} }

  let(:long_title) { {title: "a" * 251, body: "A valid body"} }
  let(:long_body) { {title: "A valid title", body: "a" * 10001} }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JourneysController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all journeys as @journeys" do
      journey = Journey.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:journeys)).to eq([journey])
    end
  end

  describe "GET show" do
    it "assigns the requested journey as @journey" do
      journey = Journey.create! valid_attributes
      get :show, {:id => journey.to_param}, valid_session
      expect(assigns(:journey)).to eq(journey)
    end
  end

  describe "GET new" do
    it "assigns a new journey as @journey" do
      get :new, {}, valid_session
      expect(assigns(:journey)).to be_a_new(Journey)
    end
  end

  describe "GET edit" do
    it "assigns the requested journey as @journey" do
      journey = Journey.create! valid_attributes
      get :edit, {:id => journey.to_param}, valid_session
      expect(assigns(:journey)).to eq(journey)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Journey" do
        expect {
          post :create, {:journey => valid_attributes}, valid_session
        }.to change(Journey, :count).by(1)
      end

      it "assigns a newly created journey as @journey" do
        post :create, {:journey => valid_attributes}, valid_session
        expect(assigns(:journey)).to be_a(Journey)
        expect(assigns(:journey)).to be_persisted
      end

      it "redirects to the created journey" do
        post :create, {:journey => valid_attributes}, valid_session
        expect(response).to redirect_to(Journey.last)
      end
    end

    describe "with blank title" do
      it "assigns a newly created but unsaved journey as @journey" do
        post :create, {:journey => blank_title}, valid_session
        expect(assigns(:journey)).to be_a_new(Journey)
      end

      it "re-renders the 'new' template" do
        post :create, {:journey => blank_title}, valid_session
        expect(response).to render_template("new")
      end
    end

    describe "with blank body" do
      it "assigns a newly created but unsaved journey as @journey" do
        post :create, {:journey => blank_body}, valid_session
        expect(assigns(:journey)).to be_a_new(Journey)
      end

      it "re-renders the 'new' template" do
        post :create, {:journey => blank_body}, valid_session
        expect(response).to render_template("new")
      end
    end

    describe "with long title" do
      it "assigns a newly created but unsaved journey as @journey" do
        post :create, {:journey => long_title}, valid_session
        expect(assigns(:journey)).to be_a_new(Journey)
      end

      it "re-renders the 'new' template" do
        post :create, {:journey => long_title}, valid_session
        expect(response).to render_template("new")
      end
    end

    describe "with long body" do
      it "assigns a newly created but unsaved journey as @journey" do
        post :create, {:journey => long_body}, valid_session
        expect(assigns(:journey)).to be_a_new(Journey)
      end

      it "re-renders the 'new' template" do
        post :create, {:journey => long_body}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        {title: "A new valid title", body: "A new valid selection of body text"}
      }

      it "updates the title" do
        journey = Journey.create! valid_attributes
        put :update, {:id => journey.to_param, :journey => new_attributes}, valid_session
        journey.reload
        expect(journey.title).to eq(new_attributes[:title])
      end

      it "updates the body" do
        journey = Journey.create! valid_attributes
        put :update, {:id => journey.to_param, :journey => new_attributes}, valid_session
        journey.reload
        expect(journey.body).to eq(new_attributes[:body])
      end

      it "assigns the requested journey as @journey" do
        journey = Journey.create! valid_attributes
        put :update, {:id => journey.to_param, :journey => valid_attributes}, valid_session
        expect(assigns(:journey)).to eq(journey)
      end

      it "redirects to the journey" do
        journey = Journey.create! valid_attributes
        put :update, {:id => journey.to_param, :journey => valid_attributes}, valid_session
        expect(response).to redirect_to(journey)
      end
    end

    describe "with blank title" do
      it "assigns the journey as @journey" do
        journey = Journey.create! valid_attributes
        put :update, {:id => journey.to_param, :journey => blank_title}, valid_session
        expect(assigns(:journey)).to eq(journey)
      end

      it "re-renders the 'edit' template" do
        journey = Journey.create! valid_attributes
        put :update, {:id => journey.to_param, :journey => blank_title}, valid_session
        expect(response).to render_template("edit")
      end
    end

    describe "with blank body" do
      it "assigns the journey as @journey" do
        journey = Journey.create! valid_attributes
        put :update, {:id => journey.to_param, :journey => blank_body}, valid_session
        expect(assigns(:journey)).to eq(journey)
      end

      it "re-renders the 'edit' template" do
        journey = Journey.create! valid_attributes
        put :update, {:id => journey.to_param, :journey => blank_body}, valid_session
        expect(response).to render_template("edit")
      end
    end 

    describe "with long title" do
      it "assigns the journey as @journey" do
        journey = Journey.create! valid_attributes
        put :update, {:id => journey.to_param, :journey => long_title}, valid_session
        expect(assigns(:journey)).to eq(journey)
      end

      it "re-renders the 'edit' template" do
        journey = Journey.create! valid_attributes
        put :update, {:id => journey.to_param, :journey => long_title}, valid_session
        expect(response).to render_template("edit")
      end
    end

    describe "with long body" do
      it "assigns the journey as @journey" do
        journey = Journey.create! valid_attributes
        put :update, {:id => journey.to_param, :journey => long_body}, valid_session
        expect(assigns(:journey)).to eq(journey)
      end

      it "re-renders the 'edit' template" do
        journey = Journey.create! valid_attributes
        put :update, {:id => journey.to_param, :journey => long_body}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested journey" do
      journey = Journey.create! valid_attributes
      expect {
        delete :destroy, {:id => journey.to_param}, valid_session
      }.to change(Journey, :count).by(-1)
    end

    it "redirects to the journeys list" do
      journey = Journey.create! valid_attributes
      delete :destroy, {:id => journey.to_param}, valid_session
      expect(response).to redirect_to(journeys_url)
    end
  end

end
